#!/bin/sh
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.npm-global/bin":$PATH
export PATH="$HOME/.gem/ruby/2.6.0/bin":$PATH
export PATH="$HOME/Library/Python/3.9/bin":$PATH
export ZK_NOTEBOOK_DIR="$HOME/notebook"
eval "$(rbenv init - zsh)"
eval "$(frum init)"
