#!/bin/sh
# For bare config
alias config='/usr/bin/git --git-dir=/Users/grantmcallister/.cfg/ --work-tree=/Users/grantmcallister'

# Colorize grep output
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
# alias cp="cp -i"
# alias rm='rm -i'

# Color the list funcition
alias ls='ls -G'


